### ISSUE TITLE
Wrong input id

### ISSUE THREAD

**Issue by CyberSaxosTiGER** [Ardakilic/Recommendify#49]
I get that error when I try to login to lastfm via your app.

```json
{
  "success": false,
  "message": "Error: No node found for selector: #id_username"
}
```

After a little debug session I found the input id is "#id_username_or_email" and not "#id_username". I fixed the issue by changing the id of the input.

```diff
diff --git a/src/repository.js b/src/repository.js
index 025bfcf..762f28f 100644
--- a/src/repository.js
+++ b/src/repository.js
@@ -18,7 +18,7 @@ const paths = {
 // The last.fm login form resources
 const lastFmResources = {
     loginFormURL: 'https://secure.last.fm/login',
-    usernameField: '#id_username',
+    usernameField: '#id_username_or_email',
     passwordField: '#id_password',
     submitButton: 'button[name="submit"]',
 };

```

**Comment by Ardakilic** [comment]
Hello, Thanks for this, to be honest I didn't check this recently because last.fm natively supports the feature this tool offers now. You can create a playlist from your recommendations and export directly to spotify or Apple music from last.fm's interface.

I've made a new commit https://github.com/Ardakilic/Recommendify/commit/6c51fa62965188ecef0ce8f9778a0bfcf6f02ace which addresses this issue. Should be fixed by now.
